---
name: KiCAD client packaging
on: # yamllint disable-line rule:truthy
  release:
    branches: master
    types:
      - published
  workflow_dispatch:

jobs:
  create_x86_64_archive:
    runs-on: macos-13
    steps:
      - name: Get latest tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: Huaqiu-Electronics/kicad-mac-builder
          releases-only: true
        id: latest-release

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install brew
        run: ./ci/x86_64-on-x86_64/bootstrap-x86_64-on_x86_64.sh

      - name: Build x86_64
        run: ./release.sh ${{ steps.latest-release.outputs.tag }} x86_64

      - name: Upload installer as asset to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.HUAQIU_ELECTRONICS_TOKEN }}
          file: ./build/dmg/kicad-unified-huaqiu-${{ steps.latest-release.outputs.tag }}-macos-arm64.dmg
          asset_name: kicad-unified-huaqiu-${{ steps.latest-release.outputs.tag }}-macos-arm64.dmg
          overwrite: true
          tag: ${{ steps.latest-release.outputs.tag }}
