name: KiCad client packaging

on:
  release:
    branches: [master]
    types: [published]
  workflow_dispatch:

jobs:
  create_kicad_archive:
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get latest tag
        id: latest-release
        uses: oprypin/find-latest-tag@v1
        with:
          repository: Huaqiu-Electronics/kicad-mac-builder
          releases-only: true

      - name: Bootstrap
        run: |
          ./ci/arm64-on-arm64/bootstrap-arm64-on-arm64.sh
          ./ci/x86_64-on-arm64/bootstrap-x86_64-on-arm64.sh

      - name: Build KiCad
        env:
          TAG: ${{ steps.latest-release.outputs.tag }}
          KICAD_REF: release/10.0
          SYMBOLS_REF: ${{ steps.latest-release.outputs.tag }}
          FOOTPRINTS_REF: ${{ steps.latest-release.outputs.tag }}
          PACKAGES3D_REF: ${{ steps.latest-release.outputs.tag }}
          TEMPLATES_REF: ${{ steps.latest-release.outputs.tag }}
          RELEASE_NAME: huaqiu-${{ steps.latest-release.outputs.tag }}-macos
          DOCS_TARBALL_URL: https://gitlab.com/kicad/services/kicad-doc/-/archive/${{ steps.latest-release.outputs.tag }}/kicad-doc-${{ steps.latest-release.outputs.tag }}.tar.gz
        run: |
          ./ci/src/make-universal-build-with-refs.sh

      - name: Upload installer as asset to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.HUAQIU_ELECTRONICS_TOKEN }}
          file: ./build/dmg/kicad-unified-huaqiu-${{ steps.latest-release.outputs.tag }}-macos-arm64.dmg
          asset_name: kicad-unified-huaqiu-${{ steps.latest-release.outputs.tag }}-macos-arm64.dmg
          overwrite: true
          tag: ${{ steps.latest-release.outputs.tag }}